//=========================================================
// src/InitDevice.c: generated by Hardware Configurator
//
// This file will be regenerated when saving a document.
// leave the sections inside the "$[...]" comment tags alone
// or they will be overwritten!!
//=========================================================

// USER INCLUDES
#include <SI_EFM8BB3_Register_Enums.h>
#include "InitDevice.h"

// USER PROTOTYPES
// USER FUNCTIONS

// $[Library Includes]
// [Library Includes]$

//==============================================================================
// enter_DefaultMode_from_RESET
//==============================================================================
extern void enter_DefaultMode_from_RESET(void) {
	// $[Config Calls]
	// Save the SFRPAGE
	uint8_t SFRPAGE_save = SFRPAGE;
	PORTS_0_enter_DefaultMode_from_RESET();
	PBCFG_0_enter_DefaultMode_from_RESET();
	CMP_0_enter_DefaultMode_from_RESET();
	HFOSC_0_enter_DefaultMode_from_RESET();
	CIP51_0_enter_DefaultMode_from_RESET();
	CLOCK_0_enter_DefaultMode_from_RESET();
	PCA_0_enter_DefaultMode_from_RESET();
	PCACH_0_enter_DefaultMode_from_RESET();
	INTERRUPT_0_enter_DefaultMode_from_RESET();
	// Restore the SFRPAGE
	SFRPAGE = SFRPAGE_save;
	// [Config Calls]$

}

extern void PBCFG_0_enter_DefaultMode_from_RESET(void) {
	// $[XBR2 - Port I/O Crossbar 2]
	/*
	 // Weak Pullups enabled 
	 // Crossbar enabled
	 // UART1 I/O unavailable at Port pin
	 // UART1 RTS1 unavailable at Port pin
	 // UART1 CTS1 unavailable at Port pin
	 */
	XBR2 = XBR2_WEAKPUD__PULL_UPS_ENABLED | XBR2_XBARE__ENABLED
			| XBR2_URT1E__DISABLED | XBR2_URT1RTSE__DISABLED
			| XBR2_URT1CTSE__DISABLED;
	// [XBR2 - Port I/O Crossbar 2]$

	// $[PRTDRV - Port Drive Strength]
	// [PRTDRV - Port Drive Strength]$

	// $[XBR0 - Port I/O Crossbar 0]
	/*
	 // UART0 I/O unavailable at Port pin
	 // SPI I/O unavailable at Port pins
	 // SMBus 0 I/O unavailable at Port pins
	 // CP0 routed to Port pin
	 // Asynchronous CP0 routed to Port pin
	 // CP1 unavailable at Port pin
	 // Asynchronous CP1 unavailable at Port pin
	 // SYSCLK unavailable at Port pin
	 */
	XBR0 = XBR0_URT0E__DISABLED | XBR0_SPI0E__DISABLED | XBR0_SMB0E__DISABLED
			| XBR0_CP0E__ENABLED | XBR0_CP0AE__ENABLED | XBR0_CP1E__DISABLED
			| XBR0_CP1AE__DISABLED | XBR0_SYSCKE__DISABLED;
	// [XBR0 - Port I/O Crossbar 0]$

	// $[XBR1 - Port I/O Crossbar 1]
	/*
	 // CEX0 routed to Port pin
	 // ECI unavailable at Port pin
	 // T0 unavailable at Port pin
	 // T1 unavailable at Port pin
	 // T2 unavailable at Port pin
	 */
	XBR1 = XBR1_PCA0ME__CEX0 | XBR1_ECIE__DISABLED | XBR1_T0E__DISABLED
			| XBR1_T1E__DISABLED | XBR1_T2E__DISABLED;
	// [XBR1 - Port I/O Crossbar 1]$

}

extern void CMP_0_enter_DefaultMode_from_RESET(void) {
	// $[CMP0MX - Comparator 0 Multiplexer Selection]
	/*
	 // External pin CMP0P.1
	 // External pin CMP0N.15
	 */
	uint8_t delay;

	CMP0MX = CMP0MX_CMXP__CMP0P1 | CMP0MX_CMXN__CMP0N15;
	// Delay to allow the comparator inputs to settle
	for (delay = 0; delay < 0x20; delay++)
		;
	// [CMP0MX - Comparator 0 Multiplexer Selection]$

	// $[CMP0CN1 - Comparator 0 Control 1]
	/*
	 // Internal Comparator DAC Reference Level = 0x1F
	 // The comparator output will always reflect the input conditions
	 */
	SFRPAGE = 0x30;
	CMP0CN1 = (0x1F << CMP0CN1_DACLVL__SHIFT) | CMP0CN1_CPINH__DISABLED;
	// [CMP0CN1 - Comparator 0 Control 1]$

	// $[CMP0MD - Comparator 0 Mode]
	/*
	 // Mode 0 
	 // Connect the CMP- input to the internal DAC output, and CMP+ is
	 //     selected by CMXP. The internal DAC uses the signal specified by CMXN
	 //     as its full-scale reference
	 // Output is inverted
	 */
	SFRPAGE = 0x00;
	CMP0MD &= ~CMP0MD_CPMD__FMASK;
	CMP0MD |= CMP0MD_INSL__CMXP_DAC | CMP0MD_CPINV__INVERT;
	// [CMP0MD - Comparator 0 Mode]$

	// $[CMP0CN0 - Comparator 0 Control 0]
	/*
	 // Comparator enabled
	 */
	CMP0CN0 |= CMP0CN0_CPEN__ENABLED;
	// [CMP0CN0 - Comparator 0 Control 0]$

}

extern void HFOSC_0_enter_DefaultMode_from_RESET(void) {
	// $[HFOCN - High Frequency Oscillator Control]
	/*
	 // Force High Frequency Oscillator 0 to run
	 // Disable High Frequency Oscillator 1 
	 */
	SFRPAGE = 0x10;
	HFOCN = HFOCN_HFO0EN__ENABLED | HFOCN_HFO1EN__DISABLED;
	// [HFOCN - High Frequency Oscillator Control]$

}

extern void PORTS_0_enter_DefaultMode_from_RESET(void) {
	// $[P0 - Port 0 Pin Latch]
	// [P0 - Port 0 Pin Latch]$

	// $[P0MDOUT - Port 0 Output Mode]
	/*
	 // P0.0 output is push-pull
	 // P0.1 output is push-pull
	 // P0.2 output is open-drain
	 // P0.3 output is push-pull
	 // P0.4 output is open-drain
	 // P0.5 output is open-drain
	 // P0.6 output is open-drain
	 // P0.7 output is open-drain
	 */
	SFRPAGE = 0x00;
	P0MDOUT = P0MDOUT_B0__PUSH_PULL | P0MDOUT_B1__PUSH_PULL
			| P0MDOUT_B2__OPEN_DRAIN | P0MDOUT_B3__PUSH_PULL
			| P0MDOUT_B4__OPEN_DRAIN | P0MDOUT_B5__OPEN_DRAIN
			| P0MDOUT_B6__OPEN_DRAIN | P0MDOUT_B7__OPEN_DRAIN;
	// [P0MDOUT - Port 0 Output Mode]$

	// $[P0MDIN - Port 0 Input Mode]
	/*
	 // P0.0 pin is configured for digital mode
	 // P0.1 pin is configured for digital mode
	 // P0.2 pin is configured for analog mode
	 // P0.3 pin is configured for digital mode
	 // P0.4 pin is configured for digital mode
	 // P0.5 pin is configured for digital mode
	 // P0.6 pin is configured for digital mode
	 // P0.7 pin is configured for digital mode
	 */
	P0MDIN = P0MDIN_B0__DIGITAL | P0MDIN_B1__DIGITAL | P0MDIN_B2__ANALOG
			| P0MDIN_B3__DIGITAL | P0MDIN_B4__DIGITAL | P0MDIN_B5__DIGITAL
			| P0MDIN_B6__DIGITAL | P0MDIN_B7__DIGITAL;
	// [P0MDIN - Port 0 Input Mode]$

	// $[P0SKIP - Port 0 Skip]
	/*
	 // P0.0 pin is not skipped by the crossbar
	 // P0.1 pin is not skipped by the crossbar
	 // P0.2 pin is skipped by the crossbar
	 // P0.3 pin is not skipped by the crossbar
	 // P0.4 pin is not skipped by the crossbar
	 // P0.5 pin is not skipped by the crossbar
	 // P0.6 pin is not skipped by the crossbar
	 // P0.7 pin is not skipped by the crossbar
	 */
	P0SKIP = P0SKIP_B0__NOT_SKIPPED | P0SKIP_B1__NOT_SKIPPED
			| P0SKIP_B2__SKIPPED | P0SKIP_B3__NOT_SKIPPED
			| P0SKIP_B4__NOT_SKIPPED | P0SKIP_B5__NOT_SKIPPED
			| P0SKIP_B6__NOT_SKIPPED | P0SKIP_B7__NOT_SKIPPED;
	// [P0SKIP - Port 0 Skip]$

	// $[P0MASK - Port 0 Mask]
	// [P0MASK - Port 0 Mask]$

	// $[P0MAT - Port 0 Match]
	// [P0MAT - Port 0 Match]$

}

extern void CLOCK_0_enter_DefaultMode_from_RESET(void) {
	// $[HFOSC1 Setup]
	// [HFOSC1 Setup]$

	// $[CLKSEL - Clock Select]
	/*
	 // Clock derived from the Internal High Frequency Oscillator 0
	 // SYSCLK is equal to selected clock source divided by 1
	 */
	SFRPAGE = 0x00;
	CLKSEL = CLKSEL_CLKSL__HFOSC0 | CLKSEL_CLKDIV__SYSCLK_DIV_1;
	while ((CLKSEL & CLKSEL_DIVRDY__BMASK) == CLKSEL_DIVRDY__NOT_READY)
		;
	// [CLKSEL - Clock Select]$

}

extern void CIP51_0_enter_DefaultMode_from_RESET(void) {
	// $[PFE0CN - Prefetch Engine Control]
	/*
	 // SYSCLK < 50 MHz
	 */
	PFE0CN = PFE0CN_FLRT__SYSCLK_BELOW_50_MHZ;
	// [PFE0CN - Prefetch Engine Control]$

}

extern void TIMER16_2_enter_DefaultMode_from_RESET(void) {
	// $[Timer Initialization]
	// Save Timer Configuration
	uint8_t TMR2CN0_TR2_save;
	TMR2CN0_TR2_save = TMR2CN0 & TMR2CN0_TR2__BMASK;
	// Stop Timer
	TMR2CN0 &= ~(TMR2CN0_TR2__BMASK);
	// [Timer Initialization]$

	// $[TMR2CN1 - Timer 2 Control 1]
	/*
	 // Capture high-to-low transitions on the configurable logic unit 0
	 //     synchronous output
	 // Timer will only reload on overflow events
	 */
	SFRPAGE = 0x10;
	TMR2CN1 = TMR2CN1_T2CSEL__CLU0_OUT | TMR2CN1_RLFSEL__NONE;
	// [TMR2CN1 - Timer 2 Control 1]$

	// $[TMR2CN0 - Timer 2 Control]
	// [TMR2CN0 - Timer 2 Control]$

	// $[TMR2H - Timer 2 High Byte]
	// [TMR2H - Timer 2 High Byte]$

	// $[TMR2L - Timer 2 Low Byte]
	// [TMR2L - Timer 2 Low Byte]$

	// $[TMR2RLH - Timer 2 Reload High Byte]
	// [TMR2RLH - Timer 2 Reload High Byte]$

	// $[TMR2RLL - Timer 2 Reload Low Byte]
	// [TMR2RLL - Timer 2 Reload Low Byte]$

	// $[TMR2CN0]
	// [TMR2CN0]$

	// $[Timer Restoration]
	// Restore Timer Configuration
	TMR2CN0 |= TMR2CN0_TR2_save;
	// [Timer Restoration]$

}

extern void INTERRUPT_0_enter_DefaultMode_from_RESET(void) {
	// $[EIE1 - Extended Interrupt Enable 1]
	/*
	 // Disable ADC0 Conversion Complete interrupt
	 // Disable ADC0 Window Comparison interrupt
	 // Enable interrupt requests generated by the comparator 0 CPRIF or CPFIF
	 //     flags
	 // Disable CP1 interrupts
	 // Disable all Port Match interrupts
	 // Disable all PCA0 interrupts
	 // Disable all SMB0 interrupts
	 // Disable Timer 3 interrupts
	 */
	EIE1 = EIE1_EADC0__DISABLED | EIE1_EWADC0__DISABLED | EIE1_ECP0__ENABLED
			| EIE1_ECP1__DISABLED | EIE1_EMAT__DISABLED | EIE1_EPCA0__DISABLED
			| EIE1_ESMB0__DISABLED | EIE1_ET3__DISABLED;
	// [EIE1 - Extended Interrupt Enable 1]$

	// $[EIE2 - Extended Interrupt Enable 2]
	// [EIE2 - Extended Interrupt Enable 2]$

	// $[EIP1H - Extended Interrupt Priority 1 High]
	/*
	 // ADC0 Conversion Complete interrupt priority MSB set to low
	 // ADC0 Window interrupt priority MSB set to low
	 // CP0 interrupt priority MSB set to high
	 // CP1 interrupt priority MSB set to low
	 // Port Match interrupt priority MSB set to low
	 // PCA0 interrupt priority MSB set to low
	 // SMB0 interrupt priority MSB set to low
	 // Timer 3 interrupt priority MSB set to low
	 */
	SFRPAGE = 0x10;
	EIP1H = EIP1H_PHADC0__LOW | EIP1H_PHWADC0__LOW | EIP1H_PHCP0__HIGH
			| EIP1H_PHCP1__LOW | EIP1H_PHMAT__LOW | EIP1H_PHPCA0__LOW
			| EIP1H_PHSMB0__LOW | EIP1H_PHT3__LOW;
	// [EIP1H - Extended Interrupt Priority 1 High]$

	// $[EIP1 - Extended Interrupt Priority 1 Low]
	// [EIP1 - Extended Interrupt Priority 1 Low]$

	// $[EIP2 - Extended Interrupt Priority 2]
	// [EIP2 - Extended Interrupt Priority 2]$

	// $[EIP2H - Extended Interrupt Priority 2 High]
	// [EIP2H - Extended Interrupt Priority 2 High]$

	// $[IE - Interrupt Enable]
	/*
	 // Enable each interrupt according to its individual mask setting
	 // Disable external interrupt 0
	 // Disable external interrupt 1
	 // Disable all SPI0 interrupts
	 // Disable all Timer 0 interrupt
	 // Disable all Timer 1 interrupt
	 // Disable Timer 2 interrupt
	 // Disable UART0 interrupt
	 */
	SFRPAGE = 0x00;
	IE = IE_EA__ENABLED | IE_EX0__DISABLED | IE_EX1__DISABLED
			| IE_ESPI0__DISABLED | IE_ET0__DISABLED | IE_ET1__DISABLED
			| IE_ET2__DISABLED | IE_ES0__DISABLED;
	// [IE - Interrupt Enable]$

	// $[IP - Interrupt Priority]
	// [IP - Interrupt Priority]$

	// $[IPH - Interrupt Priority High]
	// [IPH - Interrupt Priority High]$

}

extern void PCA_0_enter_DefaultMode_from_RESET(void) {
	// $[PCA Off]
	PCA0CN0_CR = PCA0CN0_CR__STOP;
	// [PCA Off]$

	// $[PCA0MD - PCA Mode]
	/*
	 // PCA continues to function normally while the system controller is in
	 //     Idle Mode
	 // Disable the CF interrupt
	 // System clock
	 */
	PCA0MD = PCA0MD_CIDL__NORMAL | PCA0MD_ECF__OVF_INT_DISABLED
			| PCA0MD_CPS__SYSCLK;
	// [PCA0MD - PCA Mode]$

	// $[PCA0CENT - PCA Center Alignment Enable]
	// [PCA0CENT - PCA Center Alignment Enable]$

	// $[PCA0CLR - PCA Comparator Clear Control]
	/*
	 // PCA channel
	 // Comparator 0 will be used for the comparator clear function
	 // Enable the comparator clear function on PCA channel 0
	 // Disable the comparator clear function on PCA channel 1
	 // Disable the comparator clear function on PCA channel 2
	 // Disable the comparator clear function on PCA channel 3
	 // Disable the comparator clear function on PCA channel 4
	 // Disable the comparator clear function on PCA channel 5
	 */
	PCA0CLR = PCA0CLR_CPCPOL__LOW | PCA0CLR_CPCSEL__CMP_0
			| PCA0CLR_CPCE0__ENABLED | PCA0CLR_CPCE1__DISABLED
			| PCA0CLR_CPCE2__DISABLED | PCA0CLR_CPCE3__DISABLED
			| PCA0CLR_CPCE4__DISABLED | PCA0CLR_CPCE5__DISABLED;
	// [PCA0CLR - PCA Comparator Clear Control]$

	// $[PCA0L - PCA Counter/Timer Low Byte]
	// [PCA0L - PCA Counter/Timer Low Byte]$

	// $[PCA0H - PCA Counter/Timer High Byte]
	// [PCA0H - PCA Counter/Timer High Byte]$

	// $[PCA0POL - PCA Output Polarity]
	// [PCA0POL - PCA Output Polarity]$

	// $[PCA0PWM - PCA PWM Configuration]
	// [PCA0PWM - PCA PWM Configuration]$

	// $[PCA On]
	PCA0CN0_CR = PCA0CN0_CR__RUN;
	// [PCA On]$

}

extern void PCACH_0_enter_DefaultMode_from_RESET(void) {
	// $[PCA0 Settings Save]
	// Select Capture/Compare register)
	PCA0PWM &= ~PCA0PWM_ARSEL__BMASK;
	// [PCA0 Settings Save]$

	// $[PCA0CPM0 - PCA Channel 0 Capture/Compare Mode]
	/*
	 // Disable negative edge capture
	 // Disable CCF0 interrupts
	 // Enable match function
	 // 16-bit PWM selected
	 // Disable positive edge capture
	 // Enable comparator function
	 // Enable PWM function
	 // Disable toggle function
	 */
	PCA0CPM0 = PCA0CPM0_CAPN__DISABLED | PCA0CPM0_ECCF__DISABLED
			| PCA0CPM0_MAT__ENABLED | PCA0CPM0_PWM16__16_BIT
			| PCA0CPM0_CAPP__DISABLED | PCA0CPM0_ECOM__ENABLED
			| PCA0CPM0_PWM__ENABLED | PCA0CPM0_TOG__DISABLED;
	// [PCA0CPM0 - PCA Channel 0 Capture/Compare Mode]$

	// $[PCA0CPL0 - PCA Channel 0 Capture Module Low Byte]
	/*
	 // PCA Channel 0 Capture Module Low Byte = 0xFE
	 */
	PCA0CPL0 = (0xFE << PCA0CPL0_PCA0CPL0__SHIFT);
	// [PCA0CPL0 - PCA Channel 0 Capture Module Low Byte]$

	// $[PCA0CPH0 - PCA Channel 0 Capture Module High Byte]
	/*
	 // PCA Channel 0 Capture Module High Byte = 0x7F
	 */
	PCA0CPH0 = (0x7F << PCA0CPH0_PCA0CPH0__SHIFT);
	// [PCA0CPH0 - PCA Channel 0 Capture Module High Byte]$

	// $[Auto-reload]
	// [Auto-reload]$

	// $[PCA0 Settings Restore]
	// [PCA0 Settings Restore]$

}

